name: Deployment to Elastic Beanstalk
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Populate .env.local file for Nextjs
        run: |
          touch .env.local
          echo NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_51IkOaQEp6HpNljTkMRoN8mfWDw5HFJ5PJ3YJYq1Cpv1zl7OOaCgLUYj0diZMruafeDLMAK7OJDeFE6VrMqLpFa4e00JbNp0lfO >> .env.local
          echo NEXT_PUBLIC_API_URL=https://api.onlylatest.com >> .env.local
          echo IMAGES_CLOUDFRONT_HOST="images.onlylatest.com" >> .env.local

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: onlylatest-frontend
          IMAGE_TAG: latest
        run: |
          docker build -f ./docker/Dockerfile . -t $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Generate deployment package
        run: git archive HEAD -o deploy.zip
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          version_label: 'docker-${{ steps.format-time.outputs.replaced }}'
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: onlylatest-frontend
          environment_name: Onlylatest-frontend-prod
          region: us-east-2
          deployment_package: deploy.zip
